insert into department (departmentID, departmentName, Numofworkers) values (1, 'Sales', 14);
insert into department (departmentID, departmentName, Numofworkers) values (2, 'Marketing', 7);
insert into department (departmentID, departmentName, Numofworkers) values (3, 'Human Resources', 10);
insert into department (departmentID, departmentName, Numofworkers) values (4, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (5, 'Marketing', 16);
insert into department (departmentID, departmentName, Numofworkers) values (6, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (7, 'Sales', 6);
insert into department (departmentID, departmentName, Numofworkers) values (8, 'Sales', 25);
insert into department (departmentID, departmentName, Numofworkers) values (9, 'Finance', 15);
insert into department (departmentID, departmentName, Numofworkers) values (10, 'Marketing', 7);
insert into department (departmentID, departmentName, Numofworkers) values (11, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (12, 'Sales', 5);
insert into department (departmentID, departmentName, Numofworkers) values (13, 'Human Resources', 6);
insert into department (departmentID, departmentName, Numofworkers) values (14, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (15, 'Finance', 5);
insert into department (departmentID, departmentName, Numofworkers) values (16, 'Finance', 11);
insert into department (departmentID, departmentName, Numofworkers) values (17, 'Human Resources', 19);
insert into department (departmentID, departmentName, Numofworkers) values (18, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (19, 'Marketing', 17);
insert into department (departmentID, departmentName, Numofworkers) values (20, 'Marketing', 18);
insert into department (departmentID, departmentName, Numofworkers) values (21, 'Sales', 16);
insert into department (departmentID, departmentName, Numofworkers) values (22, 'Human Resources', 21);
insert into department (departmentID, departmentName, Numofworkers) values (23, 'Finance', 15);
insert into department (departmentID, departmentName, Numofworkers) values (24, 'Sales', 25);
insert into department (departmentID, departmentName, Numofworkers) values (25, 'Marketing', 23);
insert into department (departmentID, departmentName, Numofworkers) values (26, 'Human Resources', 15);
insert into department (departmentID, departmentName, Numofworkers) values (27, 'Human Resources', 25);
insert into department (departmentID, departmentName, Numofworkers) values (28, 'Finance', 10);
insert into department (departmentID, departmentName, Numofworkers) values (29, 'Marketing', 6);
insert into department (departmentID, departmentName, Numofworkers) values (30, 'Sales', 25);
insert into department (departmentID, departmentName, Numofworkers) values (31, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (32, 'Marketing', 13);
insert into department (departmentID, departmentName, Numofworkers) values (33, 'Finance', 20);
insert into department (departmentID, departmentName, Numofworkers) values (34, 'Marketing', 19);
insert into department (departmentID, departmentName, Numofworkers) values (35, 'Sales', 19);
insert into department (departmentID, departmentName, Numofworkers) values (36, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (37, 'Marketing', 22);
insert into department (departmentID, departmentName, Numofworkers) values (38, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (39, 'Human Resources', 24);
insert into department (departmentID, departmentName, Numofworkers) values (40, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (41, 'Finance', 15);
insert into department (departmentID, departmentName, Numofworkers) values (42, 'Finance', 15);
insert into department (departmentID, departmentName, Numofworkers) values (43, 'Marketing', 18);
insert into department (departmentID, departmentName, Numofworkers) values (44, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (45, 'Sales', 22);
insert into department (departmentID, departmentName, Numofworkers) values (46, 'Sales', 16);
insert into department (departmentID, departmentName, Numofworkers) values (47, 'Marketing', 11);
insert into department (departmentID, departmentName, Numofworkers) values (48, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (49, 'Finance', 21);
insert into department (departmentID, departmentName, Numofworkers) values (50, 'Finance', 20);
insert into department (departmentID, departmentName, Numofworkers) values (51, 'Finance', 15);
insert into department (departmentID, departmentName, Numofworkers) values (52, 'Finance', 23);
insert into department (departmentID, departmentName, Numofworkers) values (53, 'Finance', 9);
insert into department (departmentID, departmentName, Numofworkers) values (54, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (55, 'Sales', 14);
insert into department (departmentID, departmentName, Numofworkers) values (56, 'Finance', 11);
insert into department (departmentID, departmentName, Numofworkers) values (57, 'Sales', 14);
insert into department (departmentID, departmentName, Numofworkers) values (58, 'Marketing', 6);
insert into department (departmentID, departmentName, Numofworkers) values (59, 'Marketing', 24);
insert into department (departmentID, departmentName, Numofworkers) values (60, 'Human Resources', 8);
insert into department (departmentID, departmentName, Numofworkers) values (61, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (62, 'Finance', 23);
insert into department (departmentID, departmentName, Numofworkers) values (63, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (64, 'Finance', 20);
insert into department (departmentID, departmentName, Numofworkers) values (65, 'Marketing', 13);
insert into department (departmentID, departmentName, Numofworkers) values (66, 'Finance', 8);
insert into department (departmentID, departmentName, Numofworkers) values (67, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (68, 'Finance', 9);
insert into department (departmentID, departmentName, Numofworkers) values (69, 'Human Resources', 7);
insert into department (departmentID, departmentName, Numofworkers) values (70, 'Marketing', 14);
insert into department (departmentID, departmentName, Numofworkers) values (71, 'Marketing', 21);
insert into department (departmentID, departmentName, Numofworkers) values (72, 'Finance', 9);
insert into department (departmentID, departmentName, Numofworkers) values (73, 'Marketing', 16);
insert into department (departmentID, departmentName, Numofworkers) values (74, 'Marketing', 23);
insert into department (departmentID, departmentName, Numofworkers) values (75, 'Finance', 25);
insert into department (departmentID, departmentName, Numofworkers) values (76, 'Marketing', 16);
insert into department (departmentID, departmentName, Numofworkers) values (77, 'Sales', 19);
insert into department (departmentID, departmentName, Numofworkers) values (78, 'Marketing', 22);
insert into department (departmentID, departmentName, Numofworkers) values (79, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (80, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (81, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (82, 'Human Resources', 5);
insert into department (departmentID, departmentName, Numofworkers) values (83, 'Marketing', 24);
insert into department (departmentID, departmentName, Numofworkers) values (84, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (85, 'Sales', 7);
insert into department (departmentID, departmentName, Numofworkers) values (86, 'Sales', 14);
insert into department (departmentID, departmentName, Numofworkers) values (87, 'Sales', 10);
insert into department (departmentID, departmentName, Numofworkers) values (88, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (89, 'Sales', 6);
insert into department (departmentID, departmentName, Numofworkers) values (90, 'Marketing', 23);
insert into department (departmentID, departmentName, Numofworkers) values (91, 'Finance', 6);
insert into department (departmentID, departmentName, Numofworkers) values (92, 'Finance', 22);
insert into department (departmentID, departmentName, Numofworkers) values (93, 'Marketing', 12);
insert into department (departmentID, departmentName, Numofworkers) values (94, 'Human Resources', 20);
insert into department (departmentID, departmentName, Numofworkers) values (95, 'Finance', 8);
insert into department (departmentID, departmentName, Numofworkers) values (96, 'Sales', 9);
insert into department (departmentID, departmentName, Numofworkers) values (97, 'Human Resources', 14);
insert into department (departmentID, departmentName, Numofworkers) values (98, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (99, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (100, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (101, 'Sales', 7);
insert into department (departmentID, departmentName, Numofworkers) values (102, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (103, 'Marketing', 20);
insert into department (departmentID, departmentName, Numofworkers) values (104, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (105, 'Marketing', 14);
insert into department (departmentID, departmentName, Numofworkers) values (106, 'Marketing', 19);
insert into department (departmentID, departmentName, Numofworkers) values (107, 'Human Resources', 23);
insert into department (departmentID, departmentName, Numofworkers) values (108, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (109, 'Marketing', 18);
insert into department (departmentID, departmentName, Numofworkers) values (110, 'Sales', 14);
insert into department (departmentID, departmentName, Numofworkers) values (111, 'Finance', 8);
insert into department (departmentID, departmentName, Numofworkers) values (112, 'Finance', 10);
insert into department (departmentID, departmentName, Numofworkers) values (113, 'Marketing', 5);
insert into department (departmentID, departmentName, Numofworkers) values (114, 'Finance', 16);
insert into department (departmentID, departmentName, Numofworkers) values (115, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (116, 'Marketing', 20);
insert into department (departmentID, departmentName, Numofworkers) values (117, 'Human Resources', 5);
insert into department (departmentID, departmentName, Numofworkers) values (118, 'Human Resources', 8);
insert into department (departmentID, departmentName, Numofworkers) values (119, 'Finance', 24);
insert into department (departmentID, departmentName, Numofworkers) values (120, 'Sales', 17);
insert into department (departmentID, departmentName, Numofworkers) values (121, 'Finance', 24);
insert into department (departmentID, departmentName, Numofworkers) values (122, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (123, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (124, 'Sales', 17);
insert into department (departmentID, departmentName, Numofworkers) values (125, 'Finance', 7);
insert into department (departmentID, departmentName, Numofworkers) values (126, 'Marketing', 23);
insert into department (departmentID, departmentName, Numofworkers) values (127, 'Finance', 16);
insert into department (departmentID, departmentName, Numofworkers) values (128, 'Sales', 5);
insert into department (departmentID, departmentName, Numofworkers) values (129, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (130, 'Sales', 19);
insert into department (departmentID, departmentName, Numofworkers) values (131, 'Marketing', 24);
insert into department (departmentID, departmentName, Numofworkers) values (132, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (133, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (134, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (135, 'Marketing', 14);
insert into department (departmentID, departmentName, Numofworkers) values (136, 'Human Resources', 6);
insert into department (departmentID, departmentName, Numofworkers) values (137, 'Sales', 6);
insert into department (departmentID, departmentName, Numofworkers) values (138, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (139, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (140, 'Human Resources', 9);
insert into department (departmentID, departmentName, Numofworkers) values (141, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (142, 'Sales', 25);
insert into department (departmentID, departmentName, Numofworkers) values (143, 'Finance', 21);
insert into department (departmentID, departmentName, Numofworkers) values (144, 'Sales', 10);
insert into department (departmentID, departmentName, Numofworkers) values (145, 'Finance', 10);
insert into department (departmentID, departmentName, Numofworkers) values (146, 'Sales', 5);
insert into department (departmentID, departmentName, Numofworkers) values (147, 'Marketing', 13);
insert into department (departmentID, departmentName, Numofworkers) values (148, 'Sales', 24);
insert into department (departmentID, departmentName, Numofworkers) values (149, 'Finance', 19);
insert into department (departmentID, departmentName, Numofworkers) values (150, 'Sales', 22);
insert into department (departmentID, departmentName, Numofworkers) values (151, 'Marketing', 12);
insert into department (departmentID, departmentName, Numofworkers) values (152, 'Marketing', 13);
insert into department (departmentID, departmentName, Numofworkers) values (153, 'Finance', 11);
insert into department (departmentID, departmentName, Numofworkers) values (154, 'Finance', 19);
insert into department (departmentID, departmentName, Numofworkers) values (155, 'Finance', 10);
insert into department (departmentID, departmentName, Numofworkers) values (156, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (157, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (158, 'Human Resources', 14);
insert into department (departmentID, departmentName, Numofworkers) values (159, 'Marketing', 19);
insert into department (departmentID, departmentName, Numofworkers) values (160, 'Finance', 21);
insert into department (departmentID, departmentName, Numofworkers) values (161, 'Sales', 15);
insert into department (departmentID, departmentName, Numofworkers) values (162, 'Sales', 15);
insert into department (departmentID, departmentName, Numofworkers) values (163, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (164, 'Finance', 20);
insert into department (departmentID, departmentName, Numofworkers) values (165, 'Human Resources', 21);
insert into department (departmentID, departmentName, Numofworkers) values (166, 'Finance', 10);
insert into department (departmentID, departmentName, Numofworkers) values (167, 'Sales', 19);
insert into department (departmentID, departmentName, Numofworkers) values (168, 'Marketing', 19);
insert into department (departmentID, departmentName, Numofworkers) values (169, 'Sales', 7);
insert into department (departmentID, departmentName, Numofworkers) values (170, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (171, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (172, 'Human Resources', 10);
insert into department (departmentID, departmentName, Numofworkers) values (173, 'Finance', 10);
insert into department (departmentID, departmentName, Numofworkers) values (174, 'Sales', 18);
insert into department (departmentID, departmentName, Numofworkers) values (175, 'Sales', 19);
insert into department (departmentID, departmentName, Numofworkers) values (176, 'Human Resources', 18);
insert into department (departmentID, departmentName, Numofworkers) values (177, 'Marketing', 5);
insert into department (departmentID, departmentName, Numofworkers) values (178, 'Sales', 17);
insert into department (departmentID, departmentName, Numofworkers) values (179, 'Human Resources', 7);
insert into department (departmentID, departmentName, Numofworkers) values (180, 'Human Resources', 25);
insert into department (departmentID, departmentName, Numofworkers) values (181, 'Marketing', 23);
insert into department (departmentID, departmentName, Numofworkers) values (182, 'Marketing', 17);
insert into department (departmentID, departmentName, Numofworkers) values (183, 'Human Resources', 5);
insert into department (departmentID, departmentName, Numofworkers) values (184, 'Finance', 11);
insert into department (departmentID, departmentName, Numofworkers) values (185, 'Sales', 18);
insert into department (departmentID, departmentName, Numofworkers) values (186, 'Human Resources', 20);
insert into department (departmentID, departmentName, Numofworkers) values (187, 'Finance', 12);
insert into department (departmentID, departmentName, Numofworkers) values (188, 'Marketing', 13);
insert into department (departmentID, departmentName, Numofworkers) values (189, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (190, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (191, 'Human Resources', 15);
insert into department (departmentID, departmentName, Numofworkers) values (192, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (193, 'Marketing', 22);
insert into department (departmentID, departmentName, Numofworkers) values (194, 'Sales', 22);
insert into department (departmentID, departmentName, Numofworkers) values (195, 'Human Resources', 19);
insert into department (departmentID, departmentName, Numofworkers) values (196, 'Finance', 8);
insert into department (departmentID, departmentName, Numofworkers) values (197, 'Marketing', 22);
insert into department (departmentID, departmentName, Numofworkers) values (198, 'Human Resources', 20);
insert into department (departmentID, departmentName, Numofworkers) values (199, 'Sales', 14);
insert into department (departmentID, departmentName, Numofworkers) values (200, 'Marketing', 12);
insert into department (departmentID, departmentName, Numofworkers) values (201, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (202, 'Sales', 7);
insert into department (departmentID, departmentName, Numofworkers) values (203, 'Human Resources', 8);
insert into department (departmentID, departmentName, Numofworkers) values (204, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (205, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (206, 'Finance', 12);
insert into department (departmentID, departmentName, Numofworkers) values (207, 'Finance', 23);
insert into department (departmentID, departmentName, Numofworkers) values (208, 'Human Resources', 15);
insert into department (departmentID, departmentName, Numofworkers) values (209, 'Human Resources', 17);
insert into department (departmentID, departmentName, Numofworkers) values (210, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (211, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (212, 'Finance', 12);
insert into department (departmentID, departmentName, Numofworkers) values (213, 'Human Resources', 17);
insert into department (departmentID, departmentName, Numofworkers) values (214, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (215, 'Human Resources', 6);
insert into department (departmentID, departmentName, Numofworkers) values (216, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (217, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (218, 'Finance', 9);
insert into department (departmentID, departmentName, Numofworkers) values (219, 'Marketing', 7);
insert into department (departmentID, departmentName, Numofworkers) values (220, 'Human Resources', 15);
insert into department (departmentID, departmentName, Numofworkers) values (221, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (222, 'Marketing', 12);
insert into department (departmentID, departmentName, Numofworkers) values (223, 'Marketing', 10);
insert into department (departmentID, departmentName, Numofworkers) values (224, 'Sales', 7);
insert into department (departmentID, departmentName, Numofworkers) values (225, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (226, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (227, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (228, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (229, 'Marketing', 18);
insert into department (departmentID, departmentName, Numofworkers) values (230, 'Finance', 21);
insert into department (departmentID, departmentName, Numofworkers) values (231, 'Marketing', 10);
insert into department (departmentID, departmentName, Numofworkers) values (232, 'Sales', 15);
insert into department (departmentID, departmentName, Numofworkers) values (233, 'Marketing', 7);
insert into department (departmentID, departmentName, Numofworkers) values (234, 'Marketing', 14);
insert into department (departmentID, departmentName, Numofworkers) values (235, 'Human Resources', 21);
insert into department (departmentID, departmentName, Numofworkers) values (236, 'Marketing', 21);
insert into department (departmentID, departmentName, Numofworkers) values (237, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (238, 'Human Resources', 25);
insert into department (departmentID, departmentName, Numofworkers) values (239, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (240, 'Finance', 25);
insert into department (departmentID, departmentName, Numofworkers) values (241, 'Marketing', 19);
insert into department (departmentID, departmentName, Numofworkers) values (242, 'Finance', 18);
insert into department (departmentID, departmentName, Numofworkers) values (243, 'Finance', 12);
insert into department (departmentID, departmentName, Numofworkers) values (244, 'Sales', 10);
insert into department (departmentID, departmentName, Numofworkers) values (245, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (246, 'Finance', 6);
insert into department (departmentID, departmentName, Numofworkers) values (247, 'Finance', 22);
insert into department (departmentID, departmentName, Numofworkers) values (248, 'Sales', 22);
insert into department (departmentID, departmentName, Numofworkers) values (249, 'Marketing', 6);
insert into department (departmentID, departmentName, Numofworkers) values (250, 'Marketing', 12);
insert into department (departmentID, departmentName, Numofworkers) values (251, 'Marketing', 6);
insert into department (departmentID, departmentName, Numofworkers) values (252, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (253, 'Human Resources', 14);
insert into department (departmentID, departmentName, Numofworkers) values (254, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (255, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (256, 'Marketing', 7);
insert into department (departmentID, departmentName, Numofworkers) values (257, 'Sales', 9);
insert into department (departmentID, departmentName, Numofworkers) values (258, 'Sales', 10);
insert into department (departmentID, departmentName, Numofworkers) values (259, 'Human Resources', 8);
insert into department (departmentID, departmentName, Numofworkers) values (260, 'Finance', 12);
insert into department (departmentID, departmentName, Numofworkers) values (261, 'Sales', 5);
insert into department (departmentID, departmentName, Numofworkers) values (262, 'Sales', 12);
insert into department (departmentID, departmentName, Numofworkers) values (263, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (264, 'Marketing', 20);
insert into department (departmentID, departmentName, Numofworkers) values (265, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (266, 'Finance', 21);
insert into department (departmentID, departmentName, Numofworkers) values (267, 'Human Resources', 9);
insert into department (departmentID, departmentName, Numofworkers) values (268, 'Sales', 11);
insert into department (departmentID, departmentName, Numofworkers) values (269, 'Marketing', 9);
insert into department (departmentID, departmentName, Numofworkers) values (270, 'Human Resources', 7);
insert into department (departmentID, departmentName, Numofworkers) values (271, 'Sales', 24);
insert into department (departmentID, departmentName, Numofworkers) values (272, 'Human Resources', 7);
insert into department (departmentID, departmentName, Numofworkers) values (273, 'Marketing', 20);
insert into department (departmentID, departmentName, Numofworkers) values (274, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (275, 'Sales', 15);
insert into department (departmentID, departmentName, Numofworkers) values (276, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (277, 'Sales', 18);
insert into department (departmentID, departmentName, Numofworkers) values (278, 'Marketing', 11);
insert into department (departmentID, departmentName, Numofworkers) values (279, 'Sales', 17);
insert into department (departmentID, departmentName, Numofworkers) values (280, 'Sales', 14);
insert into department (departmentID, departmentName, Numofworkers) values (281, 'Sales', 12);
insert into department (departmentID, departmentName, Numofworkers) values (282, 'Human Resources', 7);
insert into department (departmentID, departmentName, Numofworkers) values (283, 'Finance', 15);
insert into department (departmentID, departmentName, Numofworkers) values (284, 'Sales', 9);
insert into department (departmentID, departmentName, Numofworkers) values (285, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (286, 'Finance', 9);
insert into department (departmentID, departmentName, Numofworkers) values (287, 'Sales', 25);
insert into department (departmentID, departmentName, Numofworkers) values (288, 'Sales', 10);
insert into department (departmentID, departmentName, Numofworkers) values (289, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (290, 'Human Resources', 24);
insert into department (departmentID, departmentName, Numofworkers) values (291, 'Sales', 8);
insert into department (departmentID, departmentName, Numofworkers) values (292, 'Sales', 18);
insert into department (departmentID, departmentName, Numofworkers) values (293, 'Marketing', 19);
insert into department (departmentID, departmentName, Numofworkers) values (294, 'Sales', 12);
insert into department (departmentID, departmentName, Numofworkers) values (295, 'Finance', 20);
insert into department (departmentID, departmentName, Numofworkers) values (296, 'Marketing', 24);
insert into department (departmentID, departmentName, Numofworkers) values (297, 'Marketing', 20);
insert into department (departmentID, departmentName, Numofworkers) values (298, 'Marketing', 5);
insert into department (departmentID, departmentName, Numofworkers) values (299, 'Finance', 24);
insert into department (departmentID, departmentName, Numofworkers) values (300, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (301, 'Marketing', 9);
insert into department (departmentID, departmentName, Numofworkers) values (302, 'Sales', 7);
insert into department (departmentID, departmentName, Numofworkers) values (303, 'Human Resources', 5);
insert into department (departmentID, departmentName, Numofworkers) values (304, 'Sales', 23);
insert into department (departmentID, departmentName, Numofworkers) values (305, 'Human Resources', 23);
insert into department (departmentID, departmentName, Numofworkers) values (306, 'Human Resources', 8);
insert into department (departmentID, departmentName, Numofworkers) values (307, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (308, 'Finance', 12);
insert into department (departmentID, departmentName, Numofworkers) values (309, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (310, 'Human Resources', 24);
insert into department (departmentID, departmentName, Numofworkers) values (311, 'Human Resources', 23);
insert into department (departmentID, departmentName, Numofworkers) values (312, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (313, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (314, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (315, 'Human Resources', 25);
insert into department (departmentID, departmentName, Numofworkers) values (316, 'Sales', 25);
insert into department (departmentID, departmentName, Numofworkers) values (317, 'Marketing', 17);
insert into department (departmentID, departmentName, Numofworkers) values (318, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (319, 'Sales', 9);
insert into department (departmentID, departmentName, Numofworkers) values (320, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (321, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (322, 'Human Resources', 17);
insert into department (departmentID, departmentName, Numofworkers) values (323, 'Marketing', 7);
insert into department (departmentID, departmentName, Numofworkers) values (324, 'Human Resources', 19);
insert into department (departmentID, departmentName, Numofworkers) values (325, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (326, 'Marketing', 22);
insert into department (departmentID, departmentName, Numofworkers) values (327, 'Sales', 12);
insert into department (departmentID, departmentName, Numofworkers) values (328, 'Sales', 25);
insert into department (departmentID, departmentName, Numofworkers) values (329, 'Marketing', 16);
insert into department (departmentID, departmentName, Numofworkers) values (330, 'Finance', 16);
insert into department (departmentID, departmentName, Numofworkers) values (331, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (332, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (333, 'Human Resources', 9);
insert into department (departmentID, departmentName, Numofworkers) values (334, 'Human Resources', 15);
insert into department (departmentID, departmentName, Numofworkers) values (335, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (336, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (337, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (338, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (339, 'Sales', 5);
insert into department (departmentID, departmentName, Numofworkers) values (340, 'Finance', 9);
insert into department (departmentID, departmentName, Numofworkers) values (341, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (342, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (343, 'Human Resources', 18);
insert into department (departmentID, departmentName, Numofworkers) values (344, 'Sales', 10);
insert into department (departmentID, departmentName, Numofworkers) values (345, 'Human Resources', 6);
insert into department (departmentID, departmentName, Numofworkers) values (346, 'Marketing', 12);
insert into department (departmentID, departmentName, Numofworkers) values (347, 'Marketing', 22);
insert into department (departmentID, departmentName, Numofworkers) values (348, 'Finance', 24);
insert into department (departmentID, departmentName, Numofworkers) values (349, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (350, 'Finance', 10);
insert into department (departmentID, departmentName, Numofworkers) values (351, 'Finance', 12);
insert into department (departmentID, departmentName, Numofworkers) values (352, 'Sales', 20);
insert into department (departmentID, departmentName, Numofworkers) values (353, 'Finance', 20);
insert into department (departmentID, departmentName, Numofworkers) values (354, 'Sales', 15);
insert into department (departmentID, departmentName, Numofworkers) values (355, 'Sales', 18);
insert into department (departmentID, departmentName, Numofworkers) values (356, 'Human Resources', 12);
insert into department (departmentID, departmentName, Numofworkers) values (357, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (358, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (359, 'Marketing', 5);
insert into department (departmentID, departmentName, Numofworkers) values (360, 'Human Resources', 13);
insert into department (departmentID, departmentName, Numofworkers) values (361, 'Sales', 21);
insert into department (departmentID, departmentName, Numofworkers) values (362, 'Sales', 19);
insert into department (departmentID, departmentName, Numofworkers) values (363, 'Marketing', 9);
insert into department (departmentID, departmentName, Numofworkers) values (364, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (365, 'Sales', 13);
insert into department (departmentID, departmentName, Numofworkers) values (366, 'Marketing', 16);
insert into department (departmentID, departmentName, Numofworkers) values (367, 'Finance', 16);
insert into department (departmentID, departmentName, Numofworkers) values (368, 'Sales', 24);
insert into department (departmentID, departmentName, Numofworkers) values (369, 'Marketing', 10);
insert into department (departmentID, departmentName, Numofworkers) values (370, 'Human Resources', 17);
insert into department (departmentID, departmentName, Numofworkers) values (371, 'Finance', 13);
insert into department (departmentID, departmentName, Numofworkers) values (372, 'Marketing', 12);
insert into department (departmentID, departmentName, Numofworkers) values (373, 'Sales', 24);
insert into department (departmentID, departmentName, Numofworkers) values (374, 'Sales', 12);
insert into department (departmentID, departmentName, Numofworkers) values (375, 'Human Resources', 15);
insert into department (departmentID, departmentName, Numofworkers) values (376, 'Human Resources', 5);
insert into department (departmentID, departmentName, Numofworkers) values (377, 'Human Resources', 18);
insert into department (departmentID, departmentName, Numofworkers) values (378, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (379, 'Sales', 10);
insert into department (departmentID, departmentName, Numofworkers) values (380, 'Human Resources', 20);
insert into department (departmentID, departmentName, Numofworkers) values (381, 'Marketing', 8);
insert into department (departmentID, departmentName, Numofworkers) values (382, 'Marketing', 13);
insert into department (departmentID, departmentName, Numofworkers) values (383, 'Marketing', 25);
insert into department (departmentID, departmentName, Numofworkers) values (384, 'Marketing', 15);
insert into department (departmentID, departmentName, Numofworkers) values (385, 'Finance', 23);
insert into department (departmentID, departmentName, Numofworkers) values (386, 'Finance', 21);
insert into department (departmentID, departmentName, Numofworkers) values (387, 'Sales', 22);
insert into department (departmentID, departmentName, Numofworkers) values (388, 'Human Resources', 21);
insert into department (departmentID, departmentName, Numofworkers) values (389, 'Human Resources', 11);
insert into department (departmentID, departmentName, Numofworkers) values (390, 'Finance', 14);
insert into department (departmentID, departmentName, Numofworkers) values (391, 'Marketing', 10);
insert into department (departmentID, departmentName, Numofworkers) values (392, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (393, 'Finance', 23);
insert into department (departmentID, departmentName, Numofworkers) values (394, 'Human Resources', 22);
insert into department (departmentID, departmentName, Numofworkers) values (395, 'Human Resources', 21);
insert into department (departmentID, departmentName, Numofworkers) values (396, 'Marketing', 6);
insert into department (departmentID, departmentName, Numofworkers) values (397, 'Sales', 7);
insert into department (departmentID, departmentName, Numofworkers) values (398, 'Sales', 17);
insert into department (departmentID, departmentName, Numofworkers) values (399, 'Human Resources', 16);
insert into department (departmentID, departmentName, Numofworkers) values (400, 'Finance', 22);
